version: '3.7'
services:
  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8000:8000
    environment: 
      - DS_DB_USER
      - DS_DB_PASSWORD
      - DS_DB_HOST
      - DS_DB_NAME
      - DS_DB_PORT
      - GAS_API
      - INT_START
      - INT_END
      - THRESHOLD_LOW
      - THRESHOLD_HIGH

